

taxonomies = [
    { name = "tags", feed = false }
]

# The URL the site will be built for
base_url = "https://vikramxd.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "kronuz"

minify_html = true
[extra]

[extra.papermod]
title = "Applied Mode"
default_theme = "dark"
theme = "dark"
language_direction = "auto"
keywords = ["ML", "Engineering", "Systems"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = true
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
edit_post_url = "https://github.com/cydave/zola-theme-papermod/tree/master"
date_format = "%d %B %Y"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive"},
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "$BASE_URL/search", title = "Search" },
    { url=  "https://docs.google.com/document/d/1A8KGNkAtYyi4zIxSFWQ_mwBqhbXn8Pu_qbSNzDHwaws/edit?usp=sharing",title='Resume'}
]

home_title = "Applied Mode"
home_content =   "👋 I'm Vikram, deploying ML models in production. Specializing in Computer Vision and Diffusion Models. Worked with early-stage startups, now aiming to scale up for larger consumer base. This site documents my journey through AI's landscape – sharing learnings and occasional rants. Committed to building in public and open source. 🚀"
social_icons = [
    { url = "https://github.com/vikramxD", title = "GitHub", icon = "github" },
    { url = "https://twitter.com/V_J_S_1", title = "Twitter", icon = "twitter" },
    { url= "https://linkedin.com/in/vikramsingh178",title = "linkedin" , icon="linkedin"},
    
]
